# when obj-* is placed as first component, this menas obj-x86_64-linux-gnu or
# similar -- whatever `dh_auto_configure -Scmake -Dtests` chose.

# compiled programs
#obj-*/csgtexttest /usr/lib/openscad/testprograms/

# helper scripts
tests/cgalstlsanitytest /usr/lib/openscad/testprograms/
tests/virtualfb.sh /usr/lib/openscad/testprograms/

# i suppose we don't want proper python installation procedures, do we?
tests/test_pretty_print.py /usr/lib/openscad/testprograms/
tests/test_cmdline_tool.py /usr/lib/openscad/testprograms/
tests/export_import_pngtest.py /usr/lib/openscad/testprograms/
tests/validatestl.py /usr/lib/openscad/testprograms/
tests/shouldfail.py /usr/lib/openscad/testprograms/

# these got stripped off absoltue paths at build time
obj-*/CTestTestfile.cmake /usr/lib/openscad/testprograms/
obj-*/CTestCustom.cmake /usr/lib/openscad/testprograms/
tests/EnforceConfig.cmake /usr/lib/openscad/testprograms/


debian/openscad-testrun /usr/bin/
